### ISSUE TITLE
PPHuman pedestrian detection/tracking pipeline freezes.

### ISSUE THREAD

**Issue by gustavofuhr** [PaddlePaddle/PaddleDetection#9171]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

I tried to execute the pphuman pipeline for an image, as described [in the doc]( https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline/docs/tutorials/pphuman_mot_en.md), in CPU:

```
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_pphuman.yml \                                                                   
                                                   --image_file=1497149117844.jpg \
                                                   --device=cpu
```

It freezes after printing this:

```
-----------  Running Arguments -----------
ATTR:
  batch_size: 8
  enable: false
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/PPLCNet_x1_0_person_attribute_945_infer.zip
DET:
  batch_size: 1
  model_dir: https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_l_36e_pipeline.zip
[...]
------------------------------------------
DET  model dir:  /Users/gustavofuhr/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_pipeline
mot_model_dir model_dir:  /Users/gustavofuhr/.cache/paddle/infer_weights/mot_ppyoloe_l_36e_pipeline
KPT  model dir:  /Users/gustavofuhr/.cache/paddle/infer_weights/dark_hrnet_w32_256x192
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
```

I tried to download the models myself and specify in the config yml file, but it did not work. 
Also, the tools/infer.py test mentioned in the install instructions works fine.

### 复现环境 Environment

macos 15.0
Macbook pro M3
Python 3.10

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Sorry, we have not tested on M3. The PPHuman models will be add to [PaddleX](https://github.com/paddlepaddle/paddlex), and supported devices will also be update on PaddleX.

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
